"""Estimated API-equivalent cost for gateway requests.

The gateway's own billing runs on WorkBuddy credits: the `credit` field of a
usage row answers "how much did this request consume from the account". This
module answers a different question - "what would the same tokens have cost at
OpenRouter's listed price" - by pricing every usage row against a snapshot of
OpenRouter's model catalogue (USD per token, the model-level price OpenRouter
publishes rather than the cheapest provider behind it), converted at the
snapshot's usd_cny rate.

Every model is priced from that single source. Most carry one flat price; the
ones OpenRouter prices conditionally carry bands instead - a dearer rate above
an input-length threshold, or a rate that varies with UTC time of day - and the
row's own length and timestamp pick the band. Either way the figure is an
estimate of equivalent token cost, not what the gateway actually billed.

The snapshot is stored inline (same pattern as wb_catalog) so the Docker
image stays self-contained; `_fetch_pricing.py` refreshes it from OpenRouter,
and a `pricing/pricing.json` next to this script (or the path in
WB_PRICING_FILE) overrides the inline copy when present. All prices are per
`unit` tokens (1M) and the result is CNY; callers divide by meta.usd_cny to
show USD.

Only the Python standard library is required.
"""

import json
import os
import threading
import time

# Snapshot generated by _fetch_pricing.py - see that script for the sources
# and the refresh procedure. The inline copy is the fallback every install
# (including the Docker image) has.
_JSON = r'''
{
  "meta": {
    "generated_at": "2026-10-02T01:39:39",
    "base_currency": "CNY",
    "usd_cny": 7.1,
    "sources": {
      "openrouter": "https://openrouter.ai/api/v1/models"
    },
    "note": "单价均为「每百万 token」的美元价，取自 OpenRouter 公布的模型级价（同一模型可能由多家 provider 承接，取它默认路由那家的公布价，不是各家最低价）；按 usd_cny 折算成人民币；按条件定价的模型（输入长度阈值或 UTC 时段）另带 bands，按每条请求的输入长度与时间取档。OpenRouter 的缓存写入价与音频价，本地 usage 日志没有对应的 token 数，未计入。"
  },
  "models": {
    "deepseek-v4.1-flash": {
      "display": "deepseek-v4.1-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4.1-flash",
      "flat": {
        "input_cache_hit": 0.01,
        "input_cache_miss": 0.03,
        "output": 0.5
      }
    },
    "gpt-6-astra": {
      "display": "gpt-6-astra",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-6-astra",
      "flat": {
        "input_cache_hit": 1.0,
        "input_cache_miss": 10.0,
        "output": 50.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 2.0,
            "input_cache_miss": 20.0,
            "output": 75.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "hy4-preview-f": {
      "display": "hy4-preview-f",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview": {
      "display": "hy4-preview",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy3": {
      "display": "hy3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy3",
      "flat": {
        "input_cache_hit": 0.020625,
        "input_cache_miss": 0.0825,
        "output": 0.33
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.033,
            "input_cache_miss": 0.132,
            "output": 0.528
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.020625,
            "input_cache_miss": 0.0825,
            "output": 0.33
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "gpt-5.6-sol": {
      "display": "gpt-5.6-sol",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-sol",
      "flat": {
        "input_cache_hit": 0.2,
        "input_cache_miss": 2.0,
        "output": 10.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.4,
            "input_cache_miss": 4.0,
            "output": 15.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.6-terra": {
      "display": "gpt-5.6-terra",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-terra",
      "flat": {
        "input_cache_hit": 0.2,
        "input_cache_miss": 2.0,
        "output": 12.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.4,
            "input_cache_miss": 4.0,
            "output": 18.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.6-luna": {
      "display": "gpt-5.6-luna",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-luna",
      "flat": {
        "input_cache_hit": 0.02,
        "input_cache_miss": 0.2,
        "output": 1.2
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.04,
            "input_cache_miss": 0.4,
            "output": 1.8
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.5": {
      "display": "gpt-5.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.5",
      "flat": {
        "input_cache_hit": 0.5,
        "input_cache_miss": 5.0,
        "output": 30.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 1.0,
            "input_cache_miss": 10.0,
            "output": 45.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.4": {
      "display": "gpt-5.4",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.4",
      "flat": {
        "input_cache_hit": 0.25,
        "input_cache_miss": 2.5,
        "output": 15.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.5,
            "input_cache_miss": 5.0,
            "output": 22.5
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "grok-4.7": {
      "display": "grok-4.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "x-ai/grok-4.7",
      "flat": {
        "input_cache_hit": 0.5,
        "input_cache_miss": 2.0,
        "output": 6.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 1.0,
            "input_cache_miss": 4.0,
            "output": 12.0
          },
          "min_prompt_tokens": 200000
        }
      ]
    },
    "gpt-5.3-codex": {
      "display": "gpt-5.3-codex",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.3-codex",
      "flat": {
        "input_cache_hit": 0.175,
        "input_cache_miss": 1.75,
        "output": 14.0
      }
    },
    "gemini-3.5-flash": {
      "display": "gemini-3.5-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "google/gemini-3.5-flash",
      "flat": {
        "input_cache_hit": 0.15,
        "input_cache_miss": 1.5,
        "output": 9.0
      }
    },
    "glm-5.3": {
      "display": "glm-5.3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.3",
      "flat": {
        "input_cache_hit": 0.192,
        "input_cache_miss": 0.24,
        "output": 3.39
      }
    },
    "glm-5.3-flash": {
      "display": "glm-5.3-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.3-flash",
      "flat": {
        "input_cache_hit": 0.03,
        "input_cache_miss": 0.15,
        "output": 0.5
      }
    },
    "glm-5.2": {
      "display": "glm-5.2",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.2",
      "flat": {
        "input_cache_hit": 0.26,
        "input_cache_miss": 0.41,
        "output": 3.99
      }
    },
    "kimi-k3": {
      "display": "kimi-k3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k3",
      "flat": {
        "input_cache_hit": 0.6635,
        "input_cache_miss": 0.6635,
        "output": 10.0
      }
    },
    "kimi-k2.6": {
      "display": "kimi-k2.6",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.6",
      "flat": {
        "input_cache_hit": 0.07312,
        "input_cache_miss": 0.43415,
        "output": 1.828
      }
    },
    "hy3-x": {
      "display": "hy3-x",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy3",
      "flat": {
        "input_cache_hit": 0.020625,
        "input_cache_miss": 0.0825,
        "output": 0.33
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.033,
            "input_cache_miss": 0.132,
            "output": 0.528
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.020625,
            "input_cache_miss": 0.0825,
            "output": 0.33
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview-dev": {
      "display": "hy4-preview-dev",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview-x": {
      "display": "hy4-preview-x",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "minimax-m2.5": {
      "display": "minimax-m2.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m2.5",
      "flat": {
        "input_cache_hit": 0.027,
        "input_cache_miss": 0.27,
        "output": 1.08
      }
    },
    "glm-5v-turbo": {
      "display": "glm-5v-turbo",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5v-turbo",
      "flat": {
        "input_cache_hit": 0.24,
        "input_cache_miss": 1.2,
        "output": 4.0
      }
    },
    "glm-5.1": {
      "display": "glm-5.1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.1",
      "flat": {
        "input_cache_hit": 0.17914,
        "input_cache_miss": 0.9646,
        "output": 3.0316
      }
    },
    "glm-5.0-turbo": {
      "display": "glm-5.0-turbo",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5-turbo",
      "flat": {
        "input_cache_hit": 0.24,
        "input_cache_miss": 1.2,
        "output": 4.0
      }
    },
    "glm-4.6v": {
      "display": "glm-4.6v",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-4.6v",
      "flat": {
        "input_cache_hit": 0.05,
        "input_cache_miss": 0.3,
        "output": 0.9
      }
    },
    "kimi-k3-1": {
      "display": "kimi-k3-1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k3",
      "flat": {
        "input_cache_hit": 0.6635,
        "input_cache_miss": 0.6635,
        "output": 10.0
      }
    },
    "kimi-k2.7": {
      "display": "kimi-k2.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.7-code",
      "flat": {
        "input_cache_hit": 0.18,
        "input_cache_miss": 0.6712,
        "output": 3.35
      }
    },
    "kimi-k2.5": {
      "display": "kimi-k2.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.5",
      "flat": {
        "input_cache_hit": 0.07,
        "input_cache_miss": 0.45,
        "output": 2.25
      }
    },
    "kimi-k2-thinking": {
      "display": "kimi-k2-thinking",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2-thinking",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.6,
        "output": 2.5
      }
    },
    "minimax-m3": {
      "display": "minimax-m3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m3",
      "flat": {
        "input_cache_hit": 0.06,
        "input_cache_miss": 0.3,
        "output": 1.2
      }
    },
    "minimax-m2.7": {
      "display": "minimax-m2.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m2.7",
      "flat": {
        "input_cache_hit": 0.042,
        "input_cache_miss": 0.21,
        "output": 0.84
      }
    },
    "glm-4.6": {
      "display": "glm-4.6",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-4.6",
      "flat": {
        "input_cache_hit": 0.08,
        "input_cache_miss": 0.43,
        "output": 1.75
      }
    },
    "deepseek-v4-flash": {
      "display": "deepseek-v4-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4-flash",
      "flat": {
        "input_cache_hit": 0.008372,
        "input_cache_miss": 0.04186,
        "output": 0.08372
      }
    },
    "deepseek-v4-pro": {
      "display": "deepseek-v4-pro",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4-pro",
      "flat": {
        "input_cache_hit": 0.0174,
        "input_cache_miss": 0.2088,
        "output": 0.4176
      }
    },
    "deepseek-v3-2-volc": {
      "display": "deepseek-v3-2-volc",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v3.2",
      "flat": {
        "input_cache_hit": 0.028,
        "input_cache_miss": 0.28,
        "output": 0.42
      }
    },
    "deepseek-v3-1-volc": {
      "display": "deepseek-v3-1-volc",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3.1",
      "flat": {
        "input_cache_hit": 0.13,
        "input_cache_miss": 0.25,
        "output": 0.95
      }
    },
    "deepseek-v3-1": {
      "display": "deepseek-v3-1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3.1",
      "flat": {
        "input_cache_hit": 0.13,
        "input_cache_miss": 0.25,
        "output": 0.95
      }
    },
    "deepseek-r1-0528": {
      "display": "deepseek-r1-0528",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-r1-0528",
      "flat": {
        "input_cache_hit": 0.35,
        "input_cache_miss": 0.5,
        "output": 2.15
      }
    },
    "deepseek-v3-0324": {
      "display": "deepseek-v3-0324",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3-0324",
      "flat": {
        "input_cache_hit": 0.11,
        "input_cache_miss": 0.29,
        "output": 1.14
      }
    },
    "hunyuan-2.0-instruct": {
      "display": "hunyuan-2.0-instruct",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hunyuan-a13b-instruct",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.14,
        "output": 0.57
      }
    },
    "hunyuan-chat": {
      "display": "hunyuan-chat",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hunyuan-a13b-instruct",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.14,
        "output": 0.57
      }
    }
  }
}
'''

_INLINE = json.loads(_JSON)

_lock = threading.Lock()
_file_cache = {"key": None, "data": None}


def _candidate_file():
    """The out-of-band snapshot path, or None when none is configured."""
    env = os.environ.get("WB_PRICING_FILE")
    if env:
        return env
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "pricing", "pricing.json")
    return path if os.path.isfile(path) else None


def load_pricing():
    """The active pricing snapshot, reloaded when the file changes.

    The file (when present) wins over the inline copy so an operator can
    drop a refreshed snapshot next to the script without rebuilding; the
    inline copy keeps a broken or missing file from taking pricing down.
    """
    path = _candidate_file()
    key = ("inline", 0)
    if path:
        try:
            key = (path, os.path.getmtime(path))
        except OSError:
            path = None
            key = ("inline", 0)
    with _lock:
        if _file_cache["key"] == key and _file_cache["data"] is not None:
            return _file_cache["data"]
    data = None
    if path:
        try:
            with open(path, encoding="utf-8") as fh:
                loaded = json.load(fh)
            if isinstance(loaded, dict) and isinstance(loaded.get("models"), dict):
                data = loaded
        except Exception:
            data = None
    if data is None:
        data = _INLINE
    with _lock:
        _file_cache.update({"key": key, "data": data})
    return data


def _as_float(value, default=0.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


_WEEKDAYS = ("mon", "tue", "wed", "thu", "fri", "sat", "sun")


def _utc_parts(epoch_sec):
    """(weekday, HHMM) at UTC, the timezone the source states its bands in.

    The gateway can run in a container on UTC and the panel is opened from
    any timezone, so the lookup must not depend on the host clock's zone.
    """
    t = time.gmtime(_as_float(epoch_sec))
    return _WEEKDAYS[t.tm_wday], t.tm_hour * 100 + t.tm_min


def _band_applies(band, prompt_tokens, day, hhmm):
    """Whether a band's condition holds for this row.

    A band carries one of two conditions - a minimum input length, or a UTC
    window; the source never mixes the two within one entry.
    """
    threshold = band.get("min_prompt_tokens")
    if threshold is not None:
        return prompt_tokens >= _as_float(threshold)
    days = band.get("days")
    if days and day not in days:
        return False
    start = _as_float(band.get("start"))
    end = _as_float(band.get("end")) or 2400.0
    return start <= hhmm < end


def band_for(entry, epoch_sec, prompt_tokens=0.0):
    """The rate table for this row, with the band index it came from.

    OpenRouter prices some models conditionally: a dearer rate once the input
    passes a length threshold, or a rate that depends on UTC time of day. The
    bands are kept in the source's order and the *last* one that applies wins.
    The source lists length bands in ascending threshold order, so taking the
    last match picks the tightest one instead of the first that happens to
    fit; the window bands do not overlap, so the same rule holds for them.

    A model without bands, or a row that satisfies none of them, falls back to
    the model's own flat price - the estimate degrades to the single-price
    behaviour rather than to zero. The index is None when that happened.
    """
    bands = entry.get("bands")
    if isinstance(bands, list) and bands:
        day, hhmm = _utc_parts(epoch_sec)
        hit = None
        for index, band in enumerate(bands):
            if not isinstance(band, dict):
                continue
            if not _band_applies(band, prompt_tokens, day, hhmm):
                continue
            table = band.get("flat")
            if isinstance(table, dict):
                hit = (table, index)
        if hit:
            return hit
    table = entry.get("flat")
    return (table if isinstance(table, dict) else {}), None


def _rate_for(entry, epoch_sec, prompt_tokens, meta):
    """The rate table for this row, its band index, and the CNY factor."""
    table, band = band_for(entry, epoch_sec, prompt_tokens)
    factor = 1.0
    if str(entry.get("currency") or "").upper() == "USD":
        factor = _as_float(meta.get("usd_cny"), 1.0) or 1.0
    return table, band, factor


def _pick(rate, key, fallback=None):
    """A per-million rate, falling back to a conservative neighbour.

    A row without a cache-hit price is billed at the miss price (never
    cheaper than the reference engine), so the estimate cannot understate
    the cost.
    """
    value = rate.get(key)
    if value is None and fallback:
        value = rate.get(fallback)
    return _as_float(value)


def compute_row(row, pricing=None):
    """The estimated cost of one usage row, in CNY.

    Returns {"cny": float, "known": bool, "band": int|None}. known=False
    means the model has no price entry - cny stays 0 and the caller reports
    it as unpriced instead of guessing. band is the time-of-day band the
    row's timestamp landed in (None for the model's flat price), so callers
    can tell a time-priced row from an ordinary one.
    """
    if not row:
        return {"cny": 0.0, "known": False, "band": None}
    pricing = pricing if pricing is not None else load_pricing()
    entry = (pricing.get("models") or {}).get(row.get("model"))
    if not isinstance(entry, dict):
        return {"cny": 0.0, "known": False, "band": None}
    meta = pricing.get("meta") or {}
    unit = _as_float(entry.get("unit")) or 1000000.0
    prompt = _as_float(row.get("prompt_tokens"))
    rate, band, factor = _rate_for(entry, row.get("at"), prompt, meta)
    cached = min(_as_float(row.get("cached_tokens")), prompt)
    uncached = prompt - cached
    output = _as_float(row.get("completion_tokens"))
    miss = _pick(rate, "input_cache_miss")
    hit = _pick(rate, "input_cache_hit", "input_cache_miss")
    out_rate = _pick(rate, "output")
    cny = (uncached * miss + cached * hit + output * out_rate) / unit * factor
    return {"cny": cny, "known": True, "band": band}


def sum_rows(rows, pricing=None):
    """Batch totals: {"cny", "priced", "missing"}.

    `missing` is model id -> occurrence count for rows the snapshot cannot
    price, so the panel can point at what is not covered instead of quietly
    under-reporting.
    """
    pricing = pricing if pricing is not None else load_pricing()
    total = 0.0
    priced = 0
    missing = {}
    for row in rows or []:
        cost = compute_row(row, pricing=pricing)
        if cost["known"]:
            total += cost["cny"]
            priced += 1
        else:
            mid = str((row or {}).get("model") or "")
            missing[mid] = missing.get(mid, 0) + 1
    return {"cny": total, "priced": priced, "missing": missing}


def usd_cny():
    """The snapshot's CNY-per-USD rate, for callers that show USD."""
    try:
        return float((load_pricing().get("meta") or {}).get("usd_cny") or 1.0)
    except (TypeError, ValueError):
        return 1.0
